### ISSUE TITLE
https://github.com/kalray/metalibm/issues/new

### ISSUE THREAD

**Issue by pmallappa** [kalray/metalibm#41]
I have followed these steps.

```
$ git clone https://github.com/kalray/metalibm.git metalibm-lugdunum
$ git reset --hard origin/master

$ virtualenv -p /usr/bin/python3 .venv3
$ source .venv3/bin/activate
$  pip install git+https://gitlab.com/metalibm-dev/pythonsollya

$ PYTHONPATH=${PYTHONPATH}:`pwd` python3 metalibm_functions/ml_exp.py --precision binary32 --target x86_avx2 --output x86_avx2_exp2d.c

Traceback (most recent call last):
  File "metalibm_functions/ml_exp.py", line 30, in <module>
    import sollya
ImportError: /home/pmallapp/tmp/metalibm-lugdunum/.venv3/lib/python3.7/site-packages/sollya.cpython-37m-x86_64-linux-gnu.so: undefined symbol: sollya_lib_obj_is_externaldata

```

**Comment by nibrunie** [comment]
Hello, 
   Sorry for the inconvenience: you need the master version of sollya library. This version provide the sollya_lib_obj_is_externaldata symbol we are using. We did not update the list of requirements just yet.

regards,
@nibrunie

**Comment by nibrunie** [comment]
@pmallappa did updating sollya to master branch fix the issue ?

**Comment by math-algorithm** [comment]
I  pulled inside sollya_git repository,
Pulls from 
`https://scm.gforge.inria.fr/anonscm/git/sollya/sollya.git`
the HEAD now
`
"eec243ff 2019-06-25 Sylvain Chevillard (HEAD -> master, origin/master, origin/HEAD) Fixed a typo"
`
And the command

`PYTHONPATH=${PYTHONPATH}:$(pwd):$(pwd)/pythonsollya python3 metalibm_functions/ml_exp.py --help
`


> Traceback (most recent call last):
>   File "metalibm_functions/ml_exp.py", line 30, in <module>
>     import sollya
> ImportError: /home/pmallapp/tmp/metalibm-lugdunum/pythonsollya/sollya.so: undefined symbol: _Py_ZeroStruct
>

**Comment by nibrunie** [comment]
@math-algorithm This error often occurs when too different versions of python (2 vs 3 generally) are used: one for building a module and one when invoking it. Did you use the same version of python when building pythonsollya and when calling ml_exp.py ?

**Comment by nibrunie** [comment]
I am closing the issue for now (no activity since last December), do not hesitate to re-open it if the issue arises again.
