### ISSUE TITLE
Having gappa available causes generation to fail

### ISSUE THREAD

**Issue by IanBriggs** [kalray/metalibm#74]
If I run `python3 metalibm_functions/ml_exp.py --precision binary64 --accuracy cr` without gappa in my path generation completes and a cfile is produced.

When gappa is present then generation fails yielding:
```
function: expm1(_x_), poly_degree: 25, precision_list: [1, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double], approx_interval: [-0.34657359027997265470861606072908828403775006718013;0.34657359027997265470861606072908828403775006718013], modifiers: (absolute,)
Traceback (most recent call last):
  File "metalibm_functions/ml_exp.py", line 456, in <module>
    ml_exp.gen_implementation()
  File "<location>/metalibm/metalibm_core/core/ml_function.py", line 766, in gen_implementation
    function_group, source_code = self.fill_code_object(enable_subexpr_sharing=enable_subexpr_sharing)
  File "<location>/metalibm/metalibm_core/core/ml_function.py", line 727, in fill_code_object
    function_group = self.generate_function_list()
  File "<location>/metalibm/metalibm_core/core/ml_function.py", line 612, in generate_function_list
    self.implementation.set_scheme(self.generate_scheme())
  File "<location>/metalibm/metalibm_core/core/simple_scalar_function.py", line 60, in generate_scheme
    scalar_scheme = self.generate_scalar_scheme(vx)
  File "metalibm_functions/ml_exp.py", line 271, in generate_scalar_scheme
    poly_object, poly_approx_error = Polynomial.build_from_approximation_with_error(expm1(sollya.x), poly_degree, precision_list, approx_interval, sollya.absolute, error_function = error_function)
  File "<location>/metalibm/metalibm_core/core/polynomials.py", line 252, in build_from_approximation_with_error
    raise SollyaError()
metalibm_core.core.polynomials.SollyaError
```

Software details:

- metalibm 1.1 (sha1 git: b'"e331ee4a1b3df9ebdf581453852ac019d7c1b6da"'(clean))
- gappa 1.3.5
- sollya 7.0 based on GMP 6.2.0, MPFR 4.0.2 and MPFI 1.5.3
- asmde 0.1.0
- pythonsollya 0.4.0

**Comment by nibrunie** [comment]
Hello @IanBriggs , thank you for reporting the issue.
I think it is due to the fact that correctly rounded generation is not properly supported yet.
Using gappa makes metalibm try to find a polynomial providing an error less than half a ULP without properly conditioning it which eventually lead to a pythonsollya error when the degree is too large (ml_exp algorithm is still quite dirty: it will increase the candidate polynomial degree until it can find one that pass the error threshold test).

I would not trust the cfile generated when gappa is not installed.
